### ISSUE TITLE
When setup fails on Slave, the slave should not be deliberately taken down

### ISSUE THREAD

**Issue by tjlee0909** [box/ClusterRunner#116]
Right now, we have the slave be taken down when build_setup fails. I believe we had originally deliberately designed it this way because we feared that individual slaves might become defective, and that if a slave fails setup on a certain build, that it will likely fail setup on all subsequent builds.

After running ClusterRunner for a while, we've realized that this assumption is incorrect. Perhaps the master should keep track of how many of the slaves that it gave subjobs to (for this particular build) have failed setup--and if most/all of them have failed, fail the build instead of taking slaves offline.

**Comment by davidt23** [comment]
I think the simplest thing to do is just fail the build.  The issue of a misconfigured/rogue slave failing subsequent builds is a separate problem that can be solved separately

**Comment by nadeemahmad** [comment]
I noticed that there are a few issues (including this one) filed around ClusterRunner slaves being brought down intentionally or going down unexpectedly. We have also had various ad-hoc discussions around the topic. So, I wanted to collectively capture some thoughts around these issues to potentially see a pattern for solutions and ideas that might not emerge otherwise.

## Scenario A: Slave Is Intentionally Brought Down
There are two cases in this scenario.

1. The first case is the intentional execution of the `shutdown` command on the slave.
    - This is the intended graceful scenario where the slave is [first put in shutdown mode and eventually killed off](https://github.com/box/ClusterRunner/blob/fe1ce1996451e1eacc2d5bc234522ab413490e3e/app/master/slave.py#L192-L199).
    - The `is_in_shutdown_mode` flag is marked as `true` and the `is_alive` flag is supposed to eventually reach `false`. In this case, the slave will no longer be allocated anymore subjobs. However before it is killed off, the master will wait for all existing jobs to finish, before marking the `is_alive` flag to be false. Since the slave can still go down ungracefully, while existing jobs are finishing, this can lead to the second case in Scenario B mentioned below.
2. The second case is the intentional killing of the slave if there is a failure during `setup_build`.
    - Only the `is_alive` flag is set to `false`, as there is a `BadRequestError` raised [during the handling of the setup failure](https://github.com/box/ClusterRunner/blob/fe1ce1996451e1eacc2d5bc234522ab413490e3e/app/master/cluster_master.py#L213-L219). The `is_in_shutdown_mode` flag is **not** changed from `false` in this case.
    - This current issue #116 addresses this exact case (see discussion above).
    - Failures during `setup_build` should not result in slaves being marked dead, as one project's `setup_build` failures could bring down all ClusterRunner slaves, if enough builds of that project are executed.
    - It can also result in builds becoming immortal, as discussed in #280.

## Scenario B: Slave Goes Down Unexpectedly
There are also two cases in this scenario.

1. The first case is a slave going down unexpectedly when it is idle.
    - This doesn't result in catastrophic behavior, as the slave wasn't executing any jobs. In this case, the slave's `is_alive` flag eventually gets marked as `false`, but not until the master tries to allocate new subjobs to the slave. The master waits ~15 min for the slave to respond, before marking the slave as dead. This has been discussed in #287, #288, and #317.
2. The second is a slave going down unexpectedly while processing actual subjobs.
    - In this case, the build that triggered the subjobs that were to be processed by the now dead slave, will never complete (also resulting in the build becoming immortal). The master believes that the slave is still working on those subjobs, since the slave hasn't reported that it is finished processing them (and, of course, never will). Additionally, to my knowledge, there is no timeout for builds in ClusterRunner.
    - The `is_alive` flag stays `true` and the `is_in_shutdown_mode` flag stays `false`.

## Potential Solutions For Scenarios Above
These are some of the ideas thrown around to address the scenarios mentioned above.
- Don't kill slaves if they fail `setup_build`.
  - Addresses second case in Scenario A.
- Add build timeouts.
  - Addresses second case in Scenario B.
- Periodic check to see if each slave is still alive.
  - Addresses both cases in Scenario B.

Lastly, as a bit of an aside, ClusterRunner holds on to slave data for disconnected slaves. Currently, the only way to have an up-to-data slave list is to restart the master. [This is the initial draft for removing disconnected slaves from the slave list](https://github.com/box/ClusterRunner/commit/draft-remove-disconnected-slaves).

@josephharrington can you address any inaccuracies of my statements above and provide your thoughts?

Also, feel free to weigh in @cmcginty @tjlee0909 @wjdhollow.

**Comment by tjlee0909** [comment]
Yup, I like those three solutions. They seem pretty straight forward.
