### ISSUE TITLE
Developer Environment setup is not clear

### ISSUE THREAD

**Issue by huckphin** [box/ClusterRunner#131]
From looking at the README file, the setup instructions are not clear. I found in the README, the [Contributing guidelines](http://www.clusterrunner.com/docs/development-guide/) but there is no mention about what it takes to setup the environment there. I was confused on which version of Python was necessary for tests to work. I used virtualenv to setup my environment because Python3.4 (required to run tests) is not setup as default.

I am running on Mac OS X, and I had to run the following steps to get started.

```
# Out of band, I needed to update my Homebrew Python install to include Python3.4
# The latest version of Python I had was only Python3.3, and it did not work.

virtualenv -p `which python3.4` venv
source venv/bin/activate
pip install -r requirements.txt
```

After the install make test does _mostly_ work. I am still having trouble running the functional tests out of the box. Maybe I am missing some software, but I haven't dug into the tests to see if I am missing some software yet.

Would be nice to have it documented someplace. Would you like me to open up a PR for this? Let me know.

**Comment by josephharrington** [comment]
Hey Chad, great point -- we haven't given much attention to the contributing guidelines yet. We'll review this and make sure it is solid.

Just for reference, can you provide the error you're seeing on the functional tests?

I also just remembered that there is a bit of extra info in the [readme inside the /test directory](https://github.com/box/ClusterRunner/blob/master/test/README.md), but we should link to that or copy that info somewhere else since I don't think any reasonable person would ever think to look there. :smile:

**Comment by huckphin** [comment]
Oh hey, yeah that's perfect. Yeah, I guess if there was a link pointing to this in the README somewhere, I think that would make it easier to find these instructions.
