### ISSUE TITLE
Build Result Storage Service

### ISSUE THREAD

**Issue by nickzuber** [box/ClusterRunner#398]
Right now all of the builds information is stored on the master service which is part of the reason why we lose all the build information between restarts. We should abstract this concept of managing builds from the master into its own service. From there, we'd ultimately be able to do things like persist this information in a database.

The `BuildsManager` class could look something like this:

```python
class BuildsManager(object):
    """
    Builds manager service that stores and handles all builds.
    """

    def __init__(self):
        self._logger = get_logger(__name__)
        self._all_builds_by_id = OrderedDict()

    def get(self, build_id: int) -> Build:
        """
        Returns a build by id
        :param build_id: The id for the build whose status we are getting
        """
        build = self._all_builds_by_id.get(build_id)
        if build is None:
            raise ItemNotFoundError('Invalid build id: {}.'.format(build_id))

        return build

    def add(self, build: Build):
        """
        Add new build to collection
        """
        self._all_builds_by_id[build.id()] = build

```

All the build creation can be still done on the master, but the actual storing and distributing of those builds would be handled in `BuildsManager`.

Goals
------

The primary goal of this proposal is to move all the builds data off of the master and into an abstracted manager class. This class as it stands wouldn't change any of the current behavior in cluster runner

Notes
------

1. We can eventually pass in a session id to the `get` and `add` methods later down the line when we want to persist builds between restarts. I don't think we'd want to care about the session id in this context until we start moving things to an actual database though, but something to keep in mind. <br />
This could look something like a dictionary of session id's that each map to an ordered dictionary of builds that were created in that session. 

Questions
----------

1. Should the `BuildsManager` class be a singleton? I can't imagine a case where we'd want to have multiple instances of this class.

**Comment by josephharrington** [comment]
A few thoughts:
- It's pretty hard to comment on this suggested change without a long-term design of what we're moving towards. As you know, TJ [sketched out](https://github.com/box/ClusterRunner/issues/329) a very rough idea of what things could look like but I think that's far from final.
- I think the session id will play much less of a role (and we could probably even remove it) if we're persisting builds across restarts. Would we need a session id at all if we have a permanent unique build id? You only mentioned it in passing but I just want to state for the record that I don't think we should design anything assuming session ids will play a major or permanent role.
- Along the same lines, I think any "build storage service" (even if just a light wrapper around a db with pointers to a filesystem) should be the thing assigning ids to builds. Again, it's hard to make this call for sure without a full design, but I imagine if we were using something like a sqlish db that we'd want to use db ids instead of having ClusterRunner itself create its own concept of ids. (So maybe your BuildManager class should take over id assignment?)

**Comment by josephharrington** [comment]
We talked a bit offline. It sounds like the next step after this change will be to design whatever changes would be necessary to pull builds out into some type of persistent storage so that we could keep build metadata and results across restarts of the master service. In that context I think what you suggested above is fine; I'm not opposed and it seems like pretty low effort. I suspect that you might end up needing to add a bit more (for example to support fetching ranges of builds).

Can I suggest `BuildStore` as an alternate name to `BuildManager`? 😛

**Comment by tjlee0909** [comment]
Yeah, my main takeaways from that offline conversations were:

- We are 100% okay with persisting things across restarts in ClusterRunner.
- As a consequence of us persisting things across restarts in CR, we will no longer need the session-id. I think we are all committed to this decision moving forward.
- We aren't quite sure yet which entity (ClusterRunner? SqlLite?) will be responsible for generating the build_id, so that may affect the interface a bit.

For now, I'd move forward with whatever interface makes implementation of this initial abstraction the cleanest, and we will adjust later.

Also, 👍  to BuildStore.

**Comment by nickzuber** [comment]
@josephharrington 

> I suspect that you might end up needing to add a bit more (for example to support fetching ranges of builds)

Yeah that's a good point, I think this would depend on which service we end up using for persistence (Redis, SQLite, etc). 

In the mean time, how does something like this look? All this really does is move the builds out of the master, which I think is a good first step regardless of whichever approach we end up going with

```python
from collections import OrderedDict
from typing import List

from app.master.build import Build
from app.util.exceptions import ItemNotFoundError
from app.util.log import get_logger


class BuildStore(object):
    """
    Build storage service that stores and handles all builds.
    """

    def __init__(self):
        self._logger = get_logger(__name__)
        self._all_builds_by_id = OrderedDict()

    def get(self, build_id: int) -> Build:
        """
        Returns a build by id
        :param build_id: The id for the build whose status we are getting
        """
        build = self._all_builds_by_id.get(build_id)
        if build is None:
            raise ItemNotFoundError('Invalid build id: {}.'.format(build_id))

        return build

    def add(self, build: Build):
        """
        Add new build to collection
        """
        self._all_builds_by_id[build.id()] = build

```

Also I briefly mentioned above that we could make this a singleton, but I'm not sure if that really would matter

**Comment by ethomas2** [comment]
So it sounds like the plan is to first refactor cluster runner so that all the storing of builds happens in this BuildStore class and then to pull the build store into it's own service (wrapper around redis, or sql or something). Is that correct?

There doesn't seem to be too much point to doing the refactor first. I say we just jump straight into pulling stuff out into a separate service. We could do all the work on a separate fork/feature branch of cluster runner so you don't break master while you're working on this. My concern with doing the refactor first is that 
1. I expect there will be issues that arise when we actually pull build storage out into its own service that we won't anticipate until we actually pull it out, so a lot of the work you do in the refactor might end up becoming obsolete.
2. The refactor on its own doesn't provide any value. It'll be too easy to spin on this refactor for a week or 2 and then look back and realize we haven't gotten anything out of it.

**Comment by nickzuber** [comment]
@ethomas2 

 1. Are those two different points you're making? What kind of issues do you mean here? 
 2. The value it provides is that it makes the next step of adding a caching layer/db easier to integrate -- this way we avoid trying to move the builds out _and_ add a db in the same step. I don't really see how we can avoid doing something like this first.

Quite a few things (especially in our tests) assume the builds are on the master, so this change is an important step in the process of moving the builds to some caching layer/db.

**Comment by ethomas2** [comment]
The points are sort've the same thing. Basically I'm saying we should do everything at once because otherwise we might end up doing extra work. I guess my big concern is that I personally am not familiar with redis, if we go with redis I wouldn't be comfortable making design decisions about BuildStore without having a prototype. I'm worried about unknown unknowns, so by definition it's hard to pin down specific issues I'm worried about. That's sort've a cop out answer though, so here's my attempt to come up with a sqlite example that hopefully doesn't come across as too contrived ...

Since BuildStore has to be in charge of creating the build id, it would be reasonable to make BuildStore in charge of constructing the Build object. Those Build objects are passed all around cluster runner between different threads. Now suppose we implement BuildStore fully and later on decide to pull BuildStore out into its own service and back it up with sqlite/sqlalchemy. Sqlalchemy throws errors when you pass a db object between threads, so we wouldn't be able to attach a db object to the Build object. I feel like we could design/implement all of BuildStore without knowing about that issue, then when we introduced sqlalchemy into the equation a new problem would just "pop up".

I think I _might_ be familiar enough with sqlalchemy/sqlite to anticipate large issues before they happen without writing any code, but i'm not confident. If we go with redis I'd be much much less confident in my ability to not make mistakes without having an actual prototype.

**Comment by ethomas2** [comment]
Another point that's probably more powerful @nickzuber. You don't have that much more time left at box. I don't want your final few weeks to be spent on a refactor that doesn't doesn't buy us anything concrete. The day you leave, I want to be able to restart cluster runner and have builds persist. I don't want the code to just be refactored in such a way that would make it easier for someone else to build that feature. Realistically, if you leave before you fully implement the feature, we're not going to allocate time to finishing it.

I'm being really optimistic here, but I think you could make something that works in 1-1.5 weeks. Ignoring time spent in code-review, and fixing broken tests, and writing new tests. When you add that other stuff in, you might be able to make an mvp for persistent builds right before you leave. If you spin for a week on a refactor, I think you'll almost certainly run out of time.

**Comment by wjdhollow** [comment]
@nickzuber +1 to refactor first to place the abstraction
